### ISSUE TITLE
Question about Physical Address Constraints and Sub-Entry Storage Efficiency in TLB Design

### ISSUE THREAD

**Issue by JACKLIAO0** [0x5ec1ab/gpu-tlb#4]
Dear Authors,

Thank you for your insightful paper. I have a question regarding the design and efficiency of TLB sub-entries, specifically concerning the storage and mapping constraints within a TLB entry.

Based on the paper, I understand that each TLB entry can contain 16 sub-entries, which need to satisfy the following alignment conditions:

For 64KB pages, the virtual base addresses of the corresponding pages must be within a 1MB-aligned range.
For 2MB pages, the virtual base addresses of the corresponding pages must be within a 32MB-aligned range.
My question is about the physical address constraints for these 16 sub-entries within a single entry. Are there any alignment or continuity requirements on the physical addresses mapped by these sub-entries? If there are no such constraints, it would seem that each sub-entry would need to store a complete physical address. In this case, the design of 16 sub-entries per entry might not offer significant storage savings over simply increasing the TLB set count by 16, except for the benefit of reducing the tag storage by approximately 1/16. Is my understanding correct?

Additionally, could you please clarify the specific information stored within a TLB entry versus the information stored within each sub-entry? Understanding this distinction would be very helpful for assessing the potential benefits of sub-entry design.

Thank you for your time, and I appreciate any insights you could provide on this topic.

Best regards,
Jay

**Comment by JACKLIAO0** [comment]
Reference:
I am currently reading Zhang, Z., Allen, T., Yao, F., Gao, X., & Ge, R. (2023, November). Tunnels for Bootlegging: Fully Reverse-Engineering GPU TLBs for Challenging Isolation Guarantees of NVIDIA MIG. In Proceedings of the 2023 ACM SIGSAC Conference on Computer and Communications Security (pp. 960-974).

**Comment by 0x5ec1ab** [comment]
Hi Jay,

Thank you for your interest in our work. 

We find that contiguity in physical addresses is not necessary, so your understanding is correct -- tag space is saved.

There is also follow-up work on our sub-entry finding, which appears at MICRO this year. You can check it out (https://arxiv.org/abs/2404.18361).

**Comment by JACKLIAO0** [comment]
Dear Authors,

Thank you very much for your quick and detailed response.

Your research has provided valuable insights, and I’ve found it highly meaningful, especially considering its practical implications. After reading your recent work presented at MICRO 2024, I had an additional question. I noticed that in this new paper, the Hash Set Selection function mentioned in CCS 2023 was not used for set indexing. Could you share the reasoning behind this choice? Would the use of a Hash Set Selection function imply the need for additional bits in the tag comparison, as it wouldn’t allow us to exclude the set index bits as traditionally done by simple truncation? If so, would the Hash Set Index result in additional area and power consumption?

Additionally, have you or others explored a corresponding hardware implementation for this approach, or has NVIDIA directly adopted your idea?

Once again, thank you for your time and for engaging in this discussion. I look forward to hearing more about your thoughts.

Best regards,
Jay

**Comment by 0x5ec1ab** [comment]
Hi Jay, 
The MICRO'24 paper is not ours. I think you may want to email them to ask the question. 
Cheers :-)

**Comment by JACKLIAO0** [comment]
Sorry to bother you again. I have another question in the paper. The TLB hash selection function used VA[46:25] when the GPU page size is configured to 2MB, and [46:20] hash when the GPU page size is 64KB. In these two cases, if the HOST virtual address is accessed, the page size is 4KB, won't it cause a large number of consecutive pages to fall into the same set? Will this lead to performance degradation? Have you studied this issue? I really hope to get your answer
